"""Enhance_booking_lifecycle

Revision ID: 4eba7dfdd594
Revises: 0ad89d1cfb3a
Create Date: 2025-12-16 12:16:03.509085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eba7dfdd594'
down_revision: Union[str, Sequence[str], None] = '0ad89d1cfb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enums manually
    traveler_role = sa.Enum('PRIMARY', 'ADDITIONAL', name='traveler_role')
    traveler_role.create(op.get_bind())
    
    policy_status = sa.Enum('PASS', 'WARN', 'BLOCK', name='policy_status')
    policy_status.create(op.get_bind())
    
    booking_status = sa.Enum('draft', 'policy_evaluated', 'pending_approval', 'approved', 'confirmed', 'cancelled', 'requires_attention', 'rejected', name='booking_status')
    booking_status.create(op.get_bind())

    # Add columns
    # We use nullable=True for 'role' initially because of potential existing data, 
    # but strictly speaking we could set a default.
    op.add_column('booking_travelers', sa.Column('role', traveler_role, nullable=True))
    op.execute("UPDATE booking_travelers SET role = 'PRIMARY'") # Backfill
    op.alter_column('booking_travelers', 'role', nullable=False)
    
    op.add_column('bookings', sa.Column('policy_status', policy_status, nullable=True))
    op.add_column('bookings', sa.Column('approval_required', sa.Boolean(), server_default='false', nullable=False))
    
    # Cast Status
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(),
               type_=booking_status,
               postgresql_using='status::booking_status',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('DRAFT', 'POLICY_EVALUATED', 'PENDING_APPROVAL', 'APPROVED', 'CONFIRMED', 'CANCELLED', 'REQUIRES_ATTENTION', 'REJECTED', name='booking_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('bookings', 'approval_required')
    op.drop_column('bookings', 'policy_status')
    op.drop_column('booking_travelers', 'role')
    
    # Drop Enums
    sa.Enum(name='booking_status').drop(op.get_bind())
    sa.Enum(name='policy_status').drop(op.get_bind())
    sa.Enum(name='traveler_role').drop(op.get_bind())
    # ### end Alembic commands ###
