"""Add booking start_date and travel_class

Revision ID: 5e6303bfd9e0
Revises: a2368e19bab5
Create Date: 2025-12-18 12:24:49.422952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6303bfd9e0'
down_revision: Union[str, Sequence[str], None] = 'a2368e19bab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('travel_class', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'travel_class')
    op.drop_column('bookings', 'start_date')
    # ### end Alembic commands ###
