"""Add core corporate travel fields

Revision ID: a2368e19bab5
Revises: c7aecb5836d4
Create Date: 2025-12-18 12:03:21.076995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2368e19bab5'
down_revision: Union[str, Sequence[str], None] = 'c7aecb5836d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('department', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('division', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('cost_center', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('phone_number', sa.String(), nullable=True))
    
    # Create Enum manually
    approval_mode = postgresql.ENUM('ALWAYS_ASK', 'ONLY_WHEN_NECESSARY', name='approvalmode')
    approval_mode.create(op.get_bind())
    
    op.add_column('organizations', sa.Column('approval_mode', sa.Enum('ALWAYS_ASK', 'ONLY_WHEN_NECESSARY', name='approvalmode'), nullable=False, server_default='ALWAYS_ASK'))
    op.add_column('organizations', sa.Column('policy_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'policy_settings')
    op.drop_column('organizations', 'approval_mode')
    
    approval_mode = postgresql.ENUM('ALWAYS_ASK', 'ONLY_WHEN_NECESSARY', name='approvalmode')
    approval_mode.drop(op.get_bind())
    
    op.drop_column('employees', 'phone_number')
    op.drop_column('employees', 'cost_center')
    op.drop_column('employees', 'division')
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'job_title')
    # ### end Alembic commands ###
