"""Refactor_auth_to_SSO_SCIM

Revision ID: b6a6ad1633b1
Revises: 9842ba5173f0
Create Date: 2025-12-13 23:01:53.974530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6a6ad1633b1'
down_revision: Union[str, Sequence[str], None] = '9842ba5173f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('external_group_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directory_groups_external_group_id'), 'directory_groups', ['external_group_id'], unique=False)
    op.create_table('employee_groups',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['directory_groups.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'group_id')
    )
    op.add_column('employees', sa.Column('external_user_id', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('status', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('travel_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('employees', sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_employees_external_user_id'), 'employees', ['external_user_id'], unique=True)
    op.drop_column('employees', 'hashed_password')
    op.drop_column('employees', 'role')
    
    # Create Enum manually
    idp_type = sa.Enum('OKTA', 'AZURE_AD', 'GOOGLE_WORKSPACE', 'OTHER', name='idptype')
    idp_type.create(op.get_bind())
    
    op.add_column('organizations', sa.Column('idp_type', idp_type, nullable=True))
    op.add_column('organizations', sa.Column('scim_tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_organizations_scim_tenant_id'), 'organizations', ['scim_tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_scim_tenant_id'), table_name='organizations')
    op.drop_column('organizations', 'scim_tenant_id')
    op.drop_column('organizations', 'idp_type')
    
    # Drop Enum manually
    idp_type = sa.Enum('OKTA', 'AZURE_AD', 'GOOGLE_WORKSPACE', 'OTHER', name='idptype')
    idp_type.drop(op.get_bind())

    op.add_column('employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_employees_external_user_id'), table_name='employees')
    op.drop_column('employees', 'notification_settings')
    op.drop_column('employees', 'travel_preferences')
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    op.drop_column('employees', 'external_user_id')
    op.drop_table('employee_groups')
    op.drop_index(op.f('ix_directory_groups_external_group_id'), table_name='directory_groups')
    op.drop_table('directory_groups')
    # ### end Alembic commands ###
